buildscript {
    ext.kotlin_version = '2.3.21'
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.58'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:$kotlin_version"
        classpath 'androidx.navigation.safeargs:androidx.navigation.safeargs.gradle.plugin:2.9.8'
        classpath "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:2.0.1"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()

        maven {
            url "https://jitpack.io"
            }
    }
}

task clean(type: Delete) {
    delete rootProject.layout.buildDirectory
}
